import i18next from "eslint-plugin-i18next";
import reactHooks from "eslint-plugin-react-hooks";
import tsPlugin from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";

export default [
  {
    // Generated by tauri-specta; its `e as any` wrappers are not ours to lint.
    ignores: ["src/bindings.ts"],
  },
  {
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    plugins: {
      i18next,
      "react-hooks": reactHooks,
      "@typescript-eslint": tsPlugin,
    },
    rules: {
      // Catch text in JSX that should be translated
      "i18next/no-literal-string": [
        "error",
        {
          markupOnly: true, // Only check JSX content, not all strings
          ignoreAttribute: [
            "className",
            "style",
            "type",
            "id",
            "name",
            "key",
            "data-*",
          ], // Ignore common non-translatable attributes (aria-* and title are user-facing)
        },
      ],
      // Hook misuse is a runtime bug; stale dependency lists caused the
      // onboarding and update-checker defects fixed in the audit.
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      // AGENTS.md: strict TypeScript, no `any`.
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
];
